name: generate
on: 
  push:
    branches:
      - main

jobs:
  generate:
    strategy:
      fail-fast: false
    runs-on: macos-latest
    steps: 
      - name: Check out data
        uses: actions/checkout@v3
      - name: Build
        working-directory: ./db
        run: swift build
      - name: Run
        working-directory: ./db
        run: swift run